from __future__ import annotations

WHITESPACE_OPPORTUNITIES = [
    {
        "title": "Grammar-Guided LLM Design Agents",
        "description": "The DRC has deep expertise in design grammars/process heuristics and LLMs for design, but those threads have not yet been connected directly.",
        "related_categories": ["grammar", "ideation", "decision_making"],
        "keywords": [
            "grammar",
            "design grammar",
            "rule-based",
            "llm",
            "language model",
            "concept generation",
            "designer-valid action sequences",
        ],
    },
    {
        "title": "Ideation to Optimization Pipelines with Human-in-the-Loop",
        "description": "Ideation and optimization work are both strong, but they are still largely siloed rather than linked in end-to-end workflows.",
        "related_categories": ["ideation", "optimmization", "decision_making"],
        "keywords": [
            "ideation",
            "optimization",
            "human-in-the-loop",
            "concept generation",
            "design pipeline",
            "feedback",
            "neural operator",
        ],
    },
    {
        "title": "Marine Renewable Energy — The Missing Domain",
        "description": "Marine renewable energy appears as a strategic domain but is lightly represented in the publication history.",
        "related_categories": ["optimmization", "decision_making"],
        "keywords": [
            "marine renewable energy",
            "wave energy",
            "ocean",
            "topology optimization",
            "simulation",
            "climate",
            "infrastructure",
        ],
    },
    {
        "title": "Longitudinal AI Trust Calibration in Design Teams",
        "description": "The DRC has studied AI trust in snapshots, but not how trust evolves over repeated interactions and failures over time.",
        "related_categories": ["decision_making", "ideation"],
        "keywords": [
            "trust",
            "human-ai",
            "design teams",
            "collaboration",
            "process management",
            "longitudinal",
            "adaptive teaming",
        ],
    },
    {
        "title": "Cross-Domain Design Grammar Transfer",
        "description": "Grammar and strategy transfer have been studied within domains, but cross-domain transfer remains largely open.",
        "related_categories": ["grammar", "ideation"],
        "keywords": [
            "grammar",
            "strategy transfer",
            "cross-domain",
            "rule-based",
            "uav",
            "parametric",
            "design agents",
        ],
    },
    {
        "title": "Bias Detection and Mitigation in AI-Assisted Ideation",
        "description": "Bias in design and AI facilitation are present in the portfolio, but AI-amplified bias during ideation is still underexplored.",
        "related_categories": ["ideation", "decision_making"],
        "keywords": [
            "bias",
            "ideation",
            "ai-assisted",
            "brainstorming",
            "equity",
            "fixation",
            "anchoring",
        ],
    },
    {
        "title": "Human Preference-Driven Neural Operator Optimization",
        "description": "Neural operator work is strong, but human judgment is not yet tightly integrated into those optimization loops.",
        "related_categories": ["optimmization", "decision_making"],
        "keywords": [
            "preference",
            "neural operator",
            "optimization",
            "surrogate",
            "human preference",
            "interactive optimization",
        ],
    },
    {
        "title": "Grammar-Informed AI Process Management",
        "description": "AI process managers and grammar/sequence work exist separately; combining them would create richer adaptive facilitation.",
        "related_categories": ["grammar", "decision_making"],
        "keywords": [
            "process management",
            "grammar",
            "sequence",
            "facilitation",
            "adaptive teaming",
            "design state",
        ],
    },
    {
        "title": "Sustainability Constraints in Topology Optimization",
        "description": "Optimization work has emphasized technical performance more than lifecycle, carbon, recyclability, or end-of-life concerns.",
        "related_categories": ["optimmization"],
        "keywords": [
            "topology optimization",
            "sustainability",
            "carbon",
            "recyclability",
            "lifecycle",
            "additive manufacturing",
        ],
    },
    {
        "title": "Decision Making Under Epistemic Uncertainty in Early-Stage Design",
        "description": "Decision support is present, but ambiguous early-stage conceptual design under deep uncertainty remains a clear opportunity.",
        "related_categories": ["decision_making", "ideation"],
        "keywords": [
            "decision making",
            "uncertainty",
            "conceptual design",
            "bayesian",
            "robust decision",
            "tradeoff",
        ],
    },
    {
        "title": "Agentic AI for End-to-End UAV Mission Design",
        "description": "UAV work exists, but full mission-level agentic design remains relatively unexplored.",
        "related_categories": ["decision_making", "optimmization", "ideation"],
        "keywords": [
            "uav",
            "drone",
            "mission design",
            "agentic ai",
            "multi-agent",
            "hyform",
            "uver",
        ],
    },
    {
        "title": "Neurodivergent Cognition in AI-Assisted Design",
        "description": "Cognitive style and empathy are represented, but neurodivergent experiences with AI-assisted design tools are not.",
        "related_categories": ["ideation", "decision_making"],
        "keywords": [
            "cognitive style",
            "neurodivergent",
            "ai-assisted design",
            "inclusive design",
            "empathy",
            "participation",
        ],
    },
]
